### ISSUE TITLE
Button "define your own" on home page?

### ISSUE THREAD

**Issue by texttheater** [georgjaehnig/serchilo-drupal#117]
It just struck me that from FindFind.its home page, it is not immediately obvious that you can define your own shortcuts, which I think is an important selling point. Perhaps a button "Define your own" next to "More shortcuts" would be a nice additionn.

**Comment by georgjaehnig** [comment]
You're right. The first question is where this link should point to, to a help page? If yes, to which?

Secondly, I'm reluctant to add a fourth button, since 3 are already pretty much. Maybe as a sublink under "More shortcuts"?

**Comment by texttheater** [comment]
I'd say it should point to the "Create Shortcut" form, which in turn should have a link to the "Editing" help page somewhere at the top.

The way I see it, the purpose of this button is to draw attention to the fact that you can create your own shortcuts. Not sure if this purpose would be fulfilled if it was hidden in a submenu. I find the "Serchilo is now FindFind.it" button less important.

**Comment by georgjaehnig** [comment]
Added in 9584dd2.

**Comment by georgjaehnig** [comment]
> I find the "Serchilo is now FindFind.it" button less important.

This was added after a remark of another user. He thought at first he caught some malware after seeing the new domain findfind.it, without any reference to Serchilo.
