### ISSUE TITLE
[Suggestion] When keyword or title search has a unique (single) result, auto-open the "edit" window

### ISSUE THREAD

**Issue by Wikinaut** [georgjaehnig/serchilo-drupal#156]
When I perform a search in Findfind.it, and this search has a single result, I suggest to land on the "edit keyword" page instead to see the search result pane.

**Comment by georgjaehnig** [comment]
I afraid I can't follow. What do you refer the "search pane" to. Can you maybe give its URL?

Or maybe with a real-life example: What happens now? What should happen instead?

Thanks! :)

**Comment by georgjaehnig** [comment]
In successor www.trovu.net, editing happens now outside the UI in YAML files.
