### ISSUE TITLE
[Suggestion] Improving the output of opensearch suggestions: insert "[space]>[space]" as separator between keyword and the title (or strip-off " ( .* )" before parsing)

### ISSUE THREAD

**Issue by Wikinaut** [georgjaehnig/serchilo-drupal#157]
RE: opensearch OS suggestions (see http://www.opensearch.org/ standard).

As a user, when I have Findfind.it as default search engine installed in Firefox' searchengine bar, and when I type "some" characters, findfind.it shows suggestions beginning with "some" characters in a suggestion list box.

Currently each OS suggestion line has the format
- "keyword (title)" or 
- "keyword parameter (title)"
#### The problem

When I navigate with "cursor down" from the searchengine bar of Firefox down into the suggestion list box and press enter, FF sends the whole line back to Findfind.it (according to the OS standard, there is no other way to send or receive separate items. Only a single string (line) can be sent.)
#### Suggestion

I suggest this output format for the suggestions sent from Findfind.it to the client:
- "keyword > title"
- "keyword parameter > title"
  (this is what I prefer)

or 
- "keyword > (title)"
- "keyword parameter > (title)"
  (alternative)

I admit, that the selection of "keyword parameter" does not make sense, as the "parameter" is sent the website url(keyword).

**Comment by georgjaehnig** [comment]
But what would be better if this would be changed like suggested? Can you maybe give a real-life example that's working badly or not at all now, at how it should work?

**Comment by Wikinaut** [comment]
(I cannot make screenshots with the suggestions list)

*type "ez" into the searchengine bar.
*"ez" and further suggestions are listed now
* press "cursor down" to go into the list, position onto the item you want, e.g. "ez (Easyjet (de)"
* press enter to accept this
* (findfind receives the string "ez (Easyjet (de))" and processes this.

because "ez (Easyjet(de))" is not a known shortcut, the user's default search is fired with this as argument.

Ad hoc: strip ```" \(.*\)"``` from your inputs before you parse the input to find a keyword.

**Comment by georgjaehnig** [comment]
OK, so the goal is:

- you want to select a shortcut from the suggestions list
- and by hitting Enter go directly to the target page

OK, understood.

## possible implementation

This could be done with the current suggestion format. When receiving any query, the parser would simply look out for string matching `keyword (title)` (`title` being the current shortcut title, `keyword` the keyword). If this matches, ` (title)` would be stripped away.

The only possible problem that could arise, for example with the Google shortcut: There exits

- `g` (Google Homepage)
- `g query` (Google Search)

Now, if the user would search for `g (Google Homepage)`, he would not get the search but the homepage. But this seems to me a too rare case.

**Comment by Wikinaut** [comment]
Yes, shortcuts type II (shortcuts with one or more additional parameters) are not goal of this improvement, selection-by-cursor-navigation-into-the-list does not make sense for these type II.

In other words: the improvement targets shortcuts type I (w/o parameters) only.

**Comment by Wikinaut** [comment]
Would be nice to have your "Possible implementation" implemented (I always tend to enter fractions into the search engine input and then to go down with the cursor into the suggestions and to press enter - what currently fails).

**Comment by georgjaehnig** [comment]
Hi @Wikinaut, I'm currently pretty busy with my paid job. I have actually tried that possible implementation some weeks ago but ran into problems. For instance, the title of the shortcut isn't known at query parsing time. So I will  need to drill down more the parsing and shortcut finding process.

**Comment by Wikinaut** [comment]
@georgjaehnig you don't have to add the title at parsing time, simply clean the input _before_ you parse it: remove everything after the mere keyword i.e. $cleanedKeyword = preg_replace( "\s\(.*$", "", $dirtyKeyword).

**Comment by georgjaehnig** [comment]
> you don't have to add the title at parsing time, simply clean the input before you parse it: remove everything after the mere keyword i.e. $cleanedKeyword = preg_replace( "\s(.*$", "", $dirtyKeyword).

Well, I'm not sure if I understand your idea. Consider these two calls:

    g (Google Web Homepage)
    g (foobar)

The desired behaviour is:

- in the first case: Go to the Google Web Homepage, i.e.: call the `g` shortcut without any argument
- in the second case: Search Google with `(foobar)` as query.

So in the two cases, two different shortcuts need to be called. And the distinction works only by checking if the "argument" is the title with braces.

Do you agree?

**Comment by Wikinaut** [comment]
Any progress for this issue ? I would like to be able to select from the suggestion by using "arrow down" or the mouse, and a click.

**Comment by Wikinaut** [comment]
Also nochmal erklärt:

Wenn ich der Searchengine-Bar sagen wir "bp" eintippe, erscheint die Liste

* bp (query) beatport
* bpoc acronym (Bioportal.....)
* deu.bpo (Berlin Philharmonic ...)
* bpo 
* bpo datum
....

Nun möchte ich 

1. mit der Maus auf "bpo" klicken ; oder
1. mit dem Cursor nach unten bis auf "bpo", dann ENTER klicken

das von mir gewünschte Item (bpo) direkt auswählen (klicken) können, und findfind soll dann diesen Eintrag so behandeln, als ob ich ihn direkt eingetippt hätte ("bpo").

Es ist mir klar, dass das **nur** bei (ich nenne die so) Type-1 Shortcuts (bpo) funktioniert, nicht aber bei Type-2 Shortcuts - das sind nach meiner Nomenklatur diejenigen, die noch mindestens ein Argument erwarten (Beispiel: bpo datum).

Es gibt mehrere Ansätze, diese Aufgabe zu lösen.


Hinweis:

Das zugrundeliegende Hauptproblem ist leider *außerhalb* unserer Kontrolle, nämlich, dass der opensearch-Standard immer nur den gesamten angeklickten zum Client gesendeten und angezeigten) Text im Querystring an den Server zurückgesendet. Deshalb hatte ich mir `" >>> "` als Trenner zwischen Shortcut und Text überlegt, der beim Server (findfind Script) immer alles ab ">>>" abtrennt.

**Comment by georgjaehnig** [comment]
Hallo Wikinaut, danke für die Beschreibung, so hatte ich den Feature-Request auch verstanden. Und richtig, es gibt dafür mehrere Lösungen.

Nehmen wir als Beispiel, dass Serchilo die Query `g (Google Web Homepage)` empfängt.

1. Die eine (ich nenne sie mal "saubere") Lösung schneidet temporär das `(Google Web Homepage)` weg, prüft dann, ob es einen 0-Argument-Shortcut mit `g` findet, und wenn ja, ob `Google Web Homepage` dieses Shortcuts ist. Nur dann leitet es den User zur URL des 0-Argument-Shortcuts weiter. Wenn nicht, wird die Query nochmal als ganzes genommen und geschaut, ob es einen passenden 1-(oder mehr)-Argument-Shortcut gibt.
2. Die zweite (ich nenne sie mal "leicht gehackte") Lösung vertraut darauf, dass bei Anfragen wie `g (Google Web Homepage)` in der Klammer immer der Titel steht, der weggeschnitten werden kann. Das wird dann also immer gemacht, also auch `g (ein Text in Klammern)` wird zu `g`.
Da das aber auch anschlagen könnte, wenn jemand einfach nach einem Text in Klammern googlen möchte, schlägst Du nun vor, bei den Opensearch-Suggestions die Titel anders zu markieren, eben mit jenem ` >>> `. Das sollte dann zu weniger "False-Positives" führen (weil Suchanfragen nach `>>> irgendwas` vermutlich seltener sind).

Ich finde Ansatz 2 spontan auch besser, weil man bei 1 sonst evtl. zuviel in der Logik und im Parsing-Flow umstellen müsste. Allerdings bin ich noch nicht bei dem Trenner-String entschieden. `>>>` in den Suggestions sieht einfach nicht gut aus und nimmt auch evtl. zuviel Platz weg.

Alternativ dachte ich auch an ein UTF-8-Zeichen, zB `→`, der zum einen besser aussieht und zum anderen wohl auch seltener in Suchanfragen ist. Allerdings weiß ich hier nicht sicher, ob der auch gut in allen Browsern dargestellt wird.

Letztlich: Wenn uns nichts besseres einfällt, würde ich das aber wohl mit `→` machen. Aber wenn doch, kommentiere hier gern. :)

**Comment by Wikinaut** [comment]
Ich finde den UTF-8 Pfeil gut, erinnere mich aber daran, dass das (ich hatte genau das damals probiert) damals (Ende der 2000er Jahre) Probleme mit dem bei uns verwendeten IE6 gab. Ich teste es gerne !

" >>> " (space>>>space) sollte mit allen Browsern funktionieren. Ist ja nur ASCII.

**Comment by georgjaehnig** [comment]
OK, so I have implement it via solution 2, with the prefix `→ ` and the suffix `.`. 

It looks good on my Chrome and Firefox (most recent Mac versions).

@Wikinaut Wäre nett wenn Du auch andere browser testen könntest. Danke!

**Comment by Wikinaut** [comment]
* Firefox ESR 45.5.0 (this is the current debian 8 jessie version): ok
* Firefox 50.0 on LINUX MINT 18 Sarah: ok
* Firefox 50.0 on MAX OSX 10.11.6 El Capitan: ok 

I don't use other browsers.

For "type-2-shortcuts" like "bpo datum" (those which require further argument/s), findfind should (in these cases) open an input prompt to request the further argument/s. I think I will open a second issue for this (additional) feature. Let me know, if you want me to open it.


But current version is giant leap forwards.

**Comment by Wikinaut** [comment]
@georgjaehnig just for the design, perhaps - I don't know at the moment  - it's *schöner* to use a left-arrow  `←` as suffix (instead of using a dot `.`).
