### ISSUE TITLE
[Suggestion] When adding a new shortcut, remember the last "show/hide" setting of the "More info" and  especially the "Tags" window

### ISSUE THREAD

**Issue by Wikinaut** [georgjaehnig/serchilo-drupal#158]
When I add a new shortcut, I always have to open the input for "tags" manually ("More info" > "Tags").

I suggest to have a mechanism (user option), so that this field is always visible by default.

**Comment by georgjaehnig** [comment]
Ah, so this ticket is only about the show/hide setting of the "More info" panel, not about the contents of the Tags field, correct?

If yes, I think this could (and should) be done via a Session setting.

**Comment by Wikinaut** [comment]
Yes. I updated the issue title accordingly.

**Comment by georgjaehnig** [comment]
In successor [www.trovu.net](http://www.trovu.net/), editing happens now outside the UI in YAML files. So this became obsolete, closing.
