### ISSUE TITLE
[bug] Apostroph in keyword title "c't" not correctly encoded in the recently-changed-shortcuts feed xml

### ISSUE THREAD

**Issue by Wikinaut** [georgjaehnig/serchilo-drupal#159]
https://www.findfind.it/shortcuts.xml :+1: 

Changed shortcut with title "c't" is shown as "c&#039;t" in the feed xml.

**Comment by georgjaehnig** [comment]
I've tried to reproduce this but not sure about the error. Can you specify in the example, where exactly it is wrong:

    <item>
      <title>c&amp;#039;t</title>
      <link>http://l.ffit/shortcuts/5892/ct</link>
      <description>&lt;table&gt;
  &lt;tr&gt;&lt;td&gt;Usage:&lt;/td&gt;&lt;td&gt;&lt;strong&gt;ct&lt;/strong&gt; &lt;/td&gt;&lt;/tr&gt;
  &lt;tr&gt;&lt;td&gt;URL:&lt;/td&gt;&lt;td&gt;http://www.heise.de/ct//&lt;/td&gt;&lt;/tr&gt;
  &lt;tr&gt;&lt;td&gt;Namespace:&lt;/td&gt;&lt;td&gt;&lt;a href=&quot;/namespaces/nadazero&quot;&gt;nadazero&lt;/a&gt;&lt;/td&gt;&lt;/tr&gt;
  &lt;tr&gt;&lt;td&gt;Tags:&lt;/td&gt;&lt;td&gt;&lt;a href=&quot;/tags/publisher&quot;&gt;publisher&lt;/a&gt;, &lt;a href=&quot;/tags/magazine&quot;&gt;magazine&lt;/a&gt;, &lt;a href=&quot;/tags/software&quot;&gt;software&lt;/a&gt;, &lt;a href=&quot;/tags/hardware&quot;&gt;hardware&lt;/a&gt;&lt;/td&gt;&lt;/tr&gt;
  &lt;/table&gt;</description>
       <pubDate>Tue, 26 Jan 2016 19:00:17 +0100</pubDate>
       <dc:creator>admin</dc:creator>
       <guid isPermaLink="true">http://l.ffit/shortcuts/5892</guid>
    </item>

**Comment by georgjaehnig** [comment]
In successor [www.trovu.net](http://www.trovu.net/), there are no native RSS feeds, only on Github for the commits of the repo. So this became obsolete, closing.
