### ISSUE TITLE
Allow to register different accounts to same e-mail address

### ISSUE THREAD

**Issue by Wikinaut** [georgjaehnig/serchilo-drupal#162]
I wanted to open a new account (using the same e-mail address as used by my other account), but this was blocked.

I suggest to lift this restriction.

**Comment by jorges-intrax** [comment]
This restriction comes from Drupal.

How about using a +suffix in you email address, i.e. 

    me+first@example.com
    me+second@example.com

these are 2 different mail addresses for Drupal but both should arrive at `me@example.com`.

**Comment by georgjaehnig** [comment]
This restriction comes from Drupal.

How about using a +suffix in you email address, i.e. 

    me+first@example.com
    me+second@example.com

these are 2 different mail addresses for Drupal but both should arrive at `me@example.com`.

**Comment by Wikinaut** [comment]
This trick is however not working for my mail server. I know, that googlemail is doing something like that.
