### ISSUE TITLE
Keyword mit Umlaut "wühlmäuse" does not work in Firefox search engine bar

### ISSUE THREAD

**Issue by Wikinaut** [georgjaehnig/serchilo-drupal#164]
Bug:

The suggestion is shown, but firing te keyword "wühlmäuse" does not trigger the redirect to the target Url, but triggers my default search.

**Comment by georgjaehnig** [comment]
Yes, this is already reported in #152. Bad bug :(

**Comment by georgjaehnig** [comment]
Revert the fix. It caused other problems. Need to look more into it.
