### ISSUE TITLE
New argument type: iso639-2

### ISSUE THREAD

**Issue by texttheater** [georgjaehnig/serchilo-drupal#166]
Would be cool to have an argument type that automatically converts 2-letter language codes to 3-letter language codes. Some search forms require the latter, e.g. Tatoeba: http://tatoeba.org/eng/sentences/search?from=eng&to=ita&query=girls%20like%20cats%20more

**Comment by georgjaehnig** [comment]
That's a good idea, and simple to implement. Will be done!

**Comment by georgjaehnig** [comment]
Just rechecked the example link, and it redirects to the 2-letter language code:
https://tatoeba.org/en/sentences/search?from=eng&to=ita&query=girls%20like%20cats%20more

So closing this for now. Please reopen on https://github.com/trovu/trovu/issues if the issue appears somewhere again.

**Comment by georgjaehnig** [comment]
Edit: Not redirecting the GET params, but there also one can use 2-letter codes:
https://tatoeba.org/en/sentences/search?from=en&to=it&query=girls%20like%20cats%20more
