### ISSUE TITLE
Webpage versus Codepage: Link to "Source code" missing under "Help"

### ISSUE THREAD

**Issue by Wikinaut** [georgjaehnig/serchilo-drupal#168]
Under the "Help" button on your Webpage 

https://www.findfind.it/

I cannot find the "Source code" entry, but code for it appears to be present in

https://github.com/georgjaehnig/serchilo-drupal/blob/master/modules/serchilo/static_content/help/index.html#L15

**Comment by georgjaehnig** [comment]
Thanks for the hint, fixed it!
