### ISSUE TITLE
[Suggestion] Functional extension: Userscript based Form-fill&submit

### ISSUE THREAD

**Issue by caeschfloh** [georgjaehnig/serchilo-drupal#169]
Hi Georg, dann lass uns mal hier die Diskussion weiterführen:

seit einiger Zeit ärgere ich mich, dass immer weniger Seiten eine simple Parameterübergabe zulassen, wie es für normale ffi-Kommandos notwendig ist. Jetzt bin ich aber darauf gekommen, dass man mit einem passenden Userscript (siehe unten) das Formular mit den Parametern ausfüllen und dann absenden kann. Es funktioniert bei WIPO (caeschfloh.wipo) und sicherlich auch bei vielen anderen Seiten, die so arbeiten.

Ich frage mich, ob wir nicht ein einziges User Script bauen können, dass für alle relevanten Websites die passenden Element-IDs (document.getElementBy...("xyz")) und Parameternamen aufnimmt (schon beim Anlegen eines ffi-Kommandos) und entsprechend aktualisiert wird bei allen Nutzern über ein Hosting auf einer Userscript-Seite.

Ich denke, wir könnten uns so ein großes Feld zusätzlicher Websites erschließen.

Grüße, Ralf.

    // ==UserScript==
    // @name         WIPO
    // @namespace    http://findfind.it/
    // @version      1.0
    // @description  Simply Query WIPO
    // @author       Ralf Anders
    // @match        https://patentscope.wipo.int/search/en/search.jsf?*
    // @grant        none
    // ==/UserScript==

    function getUrlParameter(par) {

      var value='';
      var UrlParameter = window.location.search;

      if(UrlParameter !== "") {
        var i = UrlParameter.indexOf(par+"=");
        if(i >= 0) {
          i = i+par.length+1;
          var k = UrlParameter.indexOf("&", i);
          if(k < 0) {
            k = UrlParameter.length;
          }
          value = UrlParameter.substring(i, k);
          for(i=0; i<value.length; i++) {
            if(value.charAt(i) == '+') {
              value=value.substring(0, i)+" "+value.substring(i+1,value.length);
            }
          }
          value=unescape(value);
        }
      }
      return value;
    }

    var query = getUrlParameter("q");

    var queryFeld = document.getElementById("simpleSearchSearchForm:fpSearch");
    queryFeld.value = query;
    document.getElementById("simpleSearchSearchForm:commandSimpleFPSearch").click();`

**Comment by georgjaehnig** [comment]
OK, die Herausforderung ist also, dass man _bestimmte_ Inputfelder auf der
Webseite mit den übergebenen Werten befüllt. Das könnte man am besten mit einem generischen Greasemonkey-Skript erreichen, was einfach für jeden
GET-Parameter nach einem gleichnamigen `<input name="">` sucht. Beispiel

URL: http://www.example.com/?foo=search&bar=me

Das Greasemonkey-Skript muss nun

1. auf die URL gehen,
2. dort im HTML nach <input name="foo"> und <input name="bar"> suchen (nicht-gefundene Felder ignorieren)
3. diese jeweils mit "search" und "me" füllen
4. die Form abschicken

Evtl. könnte es zu Problemen kommen bei mehreren Forms, um da die
richtige zu finden, aber da könnte man dann evtl. mit weiteren
Get-Parameten die Form-ID spezifizieren. Das würde ich dann aber auf
uns zukommen lassen.

Könntest Du das obige Skript von Dir erstmal so anpassen, dass es das generisch tut? Kann Dir bei konkreten Fragen gern helfen.

Später können wir dass dann gerne bei findfind.it oder Github hosten, da wird sich noch was finden.

**Comment by caeschfloh** [comment]
Ok, das war gar nicht so viel Arbeit. Hier die erste arbeitsfähige Version, die mit ID- und Name-identifizierbaren Elementen funktioniert. Später sollten vielleicht Class und TagName noch hinzukommen. Außerdem sollten noch mehr beliebte Seiten neben Google ausgeschlossen werden, damit das Skript nicht jedes mal loslegt und ggf. für Verzögerungen sorgt (auch wenn es nach der 1. Zeile abgebrochen wird, soweit ffi-Parameter nicht =1:1). Funktionierendes WIPO-Beispiel unten angehängt und bereits entsprechend aktualisiert in ffi. 
`
// ==UserScript==
// @name         FFI_InputFillnSubmit
// @namespace    http://tampermonkey.net/
// @version      0.2
// @description  generic automatic input fill and submit
// @downloadURL  
// @author       Ralf Anders
// @match        *://*/*
// @exclude      *://*.google.*/*
// @grant        none
// ==/UserScript==


function getUrlParameter(par) {

var value='';
var UrlParameter = window.location.search;

if(UrlParameter !== "") {
var i = UrlParameter.indexOf(par+"=");
if(i >= 0) {
i = i+par.length+1;
var k = UrlParameter.indexOf("&", i);
if(k < 0) {
k = UrlParameter.length;
}
value = UrlParameter.substring(i, k);
for(i=0; i<value.length; i++) {
if(value.charAt(i) == '+') {
value=value.substring(0, i)+" "+value.substring(i+1,value.length);
}
}
value=unescape(value);
} else return 0;
}
return value;
}

// Skript nur arbeiten lassen, wenn ffi=true
if (getUrlParameter("ffi") == "1:1") {
var query = getUrlParameter("q");
var submitBy = getUrlParameter("subby");
var submitId = getUrlParameter("subid");
var submitNr = getUrlParameter("subnr"); // default: 0
var inputBy = getUrlParameter("inpby");
var inputId = getUrlParameter("inpid");
var inputNr = getUrlParameter("inpnr"); // default: 0

// fill Input, if id-identifier
if (inputBy == "id")
 {
 var queryFeld = document.getElementById(inputId);
 queryFeld.value = query;
 }

// fill Input, if name-identifier
if (inputBy == "name")
 {
 var queryFeld = document.getElementsByName(inputId)[inputNr];
 queryFeld.value = query;
 }

// submit-click, if id-identifier
if (submitBy == "id") document.getElementById(submitId).click();

// submit-click, if name-identifier
if (submitBy == "name") document.getElementsByName(submitId)[submitNr].click();
}
    
// https://patentscope.wipo.int/search/en/search.jsf?inpby=id&inpid=simpleSearchSearchForm:fpSearch&subby=id&subid=simpleSearchSearchForm:commandSimpleFPSearch&ffi=1:1&q=Liebherr
`

**Comment by caeschfloh** [comment]
[WIPO.user.js.txt](https://github.com/georgjaehnig/serchilo-drupal/files/903495/WIPO.user.js.txt)

hier wäre das Skript als Datei (txt-Endung wieder entfernen)

**Comment by caeschfloh** [comment]
[FFI_InputFillnSubmit.user.js.txt](https://github.com/georgjaehnig/serchilo-drupal/files/903508/FFI_InputFillnSubmit.user.js.txt)

hier wäre das Skript als Datei (txt-Endung wieder entfernen)

**Comment by caeschfloh** [comment]
... ich habe gerade noch die TagName-Variante implementiert und die Bundesanzeiger-Abfrage in ffi ergänzt (keyword banz). Hier wäre V0.3:

[FFI_InputFillnSubmit.user.js (2).txt](https://github.com/georgjaehnig/serchilo-drupal/files/952298/FFI_InputFillnSubmit.user.js.2.txt)

**Comment by georgjaehnig** [comment]
Lieber @caeschfloh, sorry für die späte Reaktion. Ich hab mich des Skripts jetzt mal angenommen, es ins Repo eingefügt und etwas überarbeitet. Siehe:

https://github.com/georgjaehnig/serchilo-drupal/blob/master/userscripts/fill-and-submit.user.src.js

Die Benutzung ist jetzt eine leicht andere, siehe den Documentation-Teil.

Beispielsweise wird das Bundesarchiv jetzt so aufgerufen: https://www.bundesanzeiger.de/ebanzwww/wexsservlet#serchilo[fill][%23genericsearch_param\.fulltext]=Schott&serchilo[submit]=input[type=submit]

Das Skript verwendet ein Node-JS-Modul, dieses muss mit [Browserify](http://browserify.org/) verarbeitet werden. Workflow für Development ist also

1. https://github.com/georgjaehnig/serchilo-drupal/blob/master/userscripts/fill-and-submit.user.src.js bearbeiten
2. `make fill-and-submit.user.js` aufrufen

Ich habs auf Chrome und Firefox (jeweils Mac) getestet und es läuft. Installier es Dir doch auch mal und schau, ob es läuft.

Hier noch eine weitere URL zum Testen:
https://patentscope.wipo.int/search/en/search.jsf#serchilo[fill][%23simpleSearchSearchForm\:fpSearch]=Liebherr&serchilo[submit]=%23simpleSearchSearchForm\:commandSimpleFPSearch

Beste Grüße! :)

**Comment by caeschfloh** [comment]
Ja, super, dass du jetzt Zeit gefunden hast, das kleine Projekt voranzutreiben, aber wew.. bin völlig überfordert. 
Ich habe das Skript in Tampermonkey ergänzt, Node.js installiert und browserify aktiviert.... aber jetzt? Bei deinen Links passiert erst mal nichts. Wo muss ich das make-Commando eingeben?

..aber deinen Code habe ich schon mal analysiert. Der ist ja zweifellos irgendwie cooler als meiner und dank Objektorientierung könnte man gleich mehrere Inputfelder befüllen....
Aber bei den Selektoren ist jetzt die Universalität weg... oder managt das Node.js/Browserify? 
Müsste ich mich auf alle Fälle mal einarbeiten. Auf Anhieb würde ich da kein neues FFI-Command anlegen können.

Ich frage mich, ob wir so Mitstreiter gewinnen können, wenn das nur aktive Programmierer hinbekommen   
 (ich bin ja nur ein Gelegenheitsskripter). Sind ja immerhin vier Sachen zu installieren (Skript, Tampermonkey, Node.js, Browserify) für jemand, der das nutzen will und dann muss man noch die Systematik verstehen...

Möglicherweise verstehe ich nur die Hälfte. Liebe Grüße auf alle Fälle.

**Comment by georgjaehnig** [comment]
Lieber @caeschfloh, ach sorry, da hab wohl die Doku missverständlich geschrieben. Du brauchst Node.js und Browserify gar nicht, wenn Du das Skript nur ausprobieren / nutzen willst.

Ich hab mal hier eine README geschrieben, schau mal, ob das so läuft bei Dir:
https://github.com/georgjaehnig/serchilo-drupal/tree/master/userscripts/fill-and-submit

Beste Grüße!

**Comment by caeschfloh** [comment]
Hervorragend, @georgjaehnig. Funktioniert und README ist auch gut verständlich. Besten Dank nochmal, dass du meine Anregung so engagiert aufgenommen hast. Bin gespannt, wie viele zusätzliche Queries wir jetzt noch entwickeln können. 
Hast du schon wegen Namespace entschieden, wie wir weiter vorgehen wollen?
Außerdem steht vielleicht eine Information der anderen Nutzer noch an. Mal sehen, ob noch Mitstreiter hinzukommen.

**Comment by caeschfloh** [comment]
also an dieser Seite bekomme ich den Submit-Button nicht aktiviert (Fill funktioniert). Schwieriger Selector: #brand_search > div.searchButtonContainer.bottom.right > a > span.ui-button-text

Ich habe diverse Formen erfolglos probiert, aber evtl. fehlt dem Button auch ein eventHandler oder so, sodass click() hier gar nicht geht. 

http://www.wipo.int/branddb/en/#serchilo[fill][#BRAND_input]=Siemens&serchilo[submit]=%23brand_search:div\.searchButtonContainer\.bottom\.right:a

..vielleicht hast du noch eine Idee, ob auch solche komplizierte Fälle eine Lösung haben. 
Grüße.

**Comment by caeschfloh** [comment]
...Markensuche funktioniert jedenfalls, um ein weiteres Beispiel zu haben: 
https://register.dpma.de/DPMAregister/marke/einsteiger#serchilo[fill][%23wm]=Nixdorf&serchilo[submit]=%23rechercheStarten

**Comment by georgjaehnig** [comment]
Done.
