### ISSUE TITLE
"There was a problem with your form submission. Please wait 24 seconds and try again."

### ISSUE THREAD

**Issue by texttheater** [georgjaehnig/serchilo-drupal#68]
I frequently see error messages like that while editing commands on the new site. Is this due to rate limiting? Perhaps it could be a bit more lenient. :)

**Comment by georgjaehnig** [comment]
Oh, yeah, this is rate limiting against spammers. It was also on for the "Compare" button at Shortcut revisions. Changed it so that it works only on forms where users need to enter something.
Reopen if the the problem remains.

**Comment by texttheater** [comment]
I didn't use "Compare", I manage to hit the limit with "Save" and "Delete" buttons alone.

**Comment by georgjaehnig** [comment]
OK, changed the limit to 2 seconds.

**Comment by texttheater** [comment]
Hm, still seeing the message, and the waiting time keeps getting longer. 404 seconds now.

**Comment by georgjaehnig** [comment]
OK, just removed the limit at all.
Yes, the waiting time grows, if the user hits again within the limit.
