### ISSUE TITLE
Cannot delete my own shortcuts

### ISSUE THREAD

**Issue by texttheater** [georgjaehnig/serchilo-drupal#70]
Some shortcuts in my namespace (kevang) do not have the "Delete" tab although I'm logged in. I think this concerns exactly those shortcuts created through the old Serchilo. Newly created ones do have the Delete tab.

**Comment by georgjaehnig** [comment]
Confirmed. Happens because on import, the owners were not set.

**Comment by georgjaehnig** [comment]
After having applies the [new maintenance code](https://github.com/georgjaehnig/serchilo-drupal/blob/master/modules/serchilo/serchilo.drush.inc#L55-L93), this should be resolved.
