### ISSUE TITLE
Users can change namespace of shortcut they don’t own

### ISSUE THREAD

**Issue by texttheater** [georgjaehnig/serchilo-drupal#72]
To test, I just edited this shortcut:

http://serchilo.org/shortcuts/8/google-de

I changed the namespace from deu to kevang. This worked without the need for approval. Not sure this is intended behavior. If I’m not mistaken, it allows people to remove shortcuts from other namespaces.

**Comment by georgjaehnig** [comment]
Confirmed. The problem is caused because the check is performed on the new namespace, not the old namespace. Thus, because the new namespace is a user namespace and user are free in their namespace, the edit passes.
Solution: Check on the old namespace (before the edit).

**Comment by georgjaehnig** [comment]
Solution implemented.
