### ISSUE TITLE
URL parameter syntax

### ISSUE THREAD

**Issue by georgjaehnig** [georgjaehnig/serchilo-drupal#94]
I plan to change the URL parameter syntax (again) – which I want to discuss beforehand.

# Current syntax

Currently, the syntax [follows the OpenSearch template syntax](http://www.serchilo.net/help/url). In short, this means that

1. arguments get prefixed with 's:' (for Serchilo), e.g.:

   `{s:query}`

2. variables get a category prefix or no prefix, e.g.

   `{language}`
   `{user:name}`

# New syntax

The new syntax shall better distinguish between variables and arguments, and allow further extensions. For old Serchilo users, it will look familiar to the pre-2013 syntax.

It shall come with two main concepts:

1. Arguments are prefixed with `%`, Variables with `$`. For example:

   `{%query}`
   `{$language}`
   `{$user:name}`

2. Optional key/value pairs can be added, separated by `|`. For example:

   `{%Datum|type=date|output=Y-m-d}`
   `{%second argument|order=2}`
   `{%city|function=de.city}`

(The key/value names in the examples are not relevant right now but they show about what extentions I am thinking of.)

# Discussion

With these changes, the syntax is not compatible anymore to OpenSearch. But actually, it wasn't even now, as OpenSearch [seems to have required the `{searchTerms}` parameter](http://www.opensearch.org/Specifications/OpenSearch/1.1#Required_template_parameters
) which wasn't present in Serchilo URLs. And the new syntax gives more clarity – and allows a lot of more extensions.

What I am asking you now:

1. Is the syntax clear and self-explaining?
2. Do you know of other, already-established URL syntaxes that would also suit our needs?

And if all is OK, then a simple "Yes, looks good" would also help. :)

**Comment by jneubarth-ai** [comment]
+1 for the possibility to specify the output format of dates. I use two Serchilo commands frequently where the date formats differ, so that would be a useful feature. Does it make sense to specify the input format as well or is there a default for this?

Concerning the `{%second argument|order=2}`: Shouldn't the key be `index` instead of `order`? Or maybe I'm missing the purpose of this extension.

**Comment by georgjaehnig** [comment]
Hi @jneubarth-ai, you're right, `index` would be a better name. I elaborated on this in the new issue #95.

**Comment by georgjaehnig** [comment]
@jneubarth-ai And here's some elaboration on the date format: #96.

**Comment by georgjaehnig** [comment]
Done between e481d3f and 6dcc320.
